# Model Config - Real Paired Test Model

# for custom tokenizer
vocab_size: 33
pad_token_id: 1
mask_token_id: 32

## Model Size
# Model Dimensions - 350M
num_attention_heads: 20
num_hidden_layers: 32
hidden_size: 960
intermediate_size: 3840

max_position_embeddings: 322
position_embedding_type: "rotary"

# Tokenizer
tokenizer_path: "facebook/esm2_t33_650M_UR50D"
separator: "<cls>"
padding: "max_length"
truncation: True
max_length: 320
num_processes: 128

# Datasets
datasets:
  train: "/mnt/data/datasets/ablm-training-data/v2026-05-03/train.parquet"
  eval: "/mnt/data/datasets/ablm-training-data/v2026-05-03/eval.parquet"
file_type: "parquet"

# Collator
mlm: True
mlm_probability: 0.15

# Training Arguments
run_name: "real-paired_mlm_350M_${date}"
fp16: True
seed: 42
per_device_train_batch_size: 32
per_device_eval_batch_size: 32
gradient_accumulation_steps: 1
logging_steps: 500
eval_strategy: "steps"
eval_steps: 10000

warmup_steps: 1200
max_steps: 20000

lr_scheduler_type: "linear"
learning_rate: 0.0001
weight_decay: 0.01

# Logging
output_dir: "./output/${run_name}"
report_to: "wandb"
wandb_project: "coreweave_tests"
wandb_group: "initial_testing"
logging_first_step: True
logging_dir: "./logs/${run_name}"

# Saving
save_strategy: "steps"
save_steps: 10000
